// <auto-generated />
using System;
using Dal.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241109202521_AddQuizTable")]
    partial class AddQuizTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dal.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<float>("EntryPrice")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("EntryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("ExitPrice")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset?>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Prediction")
                        .HasColumnType("integer");

                    b.Property<float>("PredictionAmount")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("PredictionTimeframe")
                        .HasColumnType("interval");

                    b.Property<int?>("Res")
                        .HasColumnType("integer");

                    b.Property<float?>("ResultPayout")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Dal.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coin = 0,
                            Value = 0f
                        },
                        new
                        {
                            Id = 2,
                            Coin = 1,
                            Value = 0f
                        },
                        new
                        {
                            Id = 3,
                            Coin = 2,
                            Value = 0f
                        });
                });

            modelBuilder.Entity("Dal.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quiz");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = 4
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = 4
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = 2
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = 2
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = 2
                        });
                });

            modelBuilder.Entity("Dal.Entities.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FriendsInvited")
                        .HasColumnType("integer");

                    b.Property<string>("ReferralSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("VisitedOtherUserReferralLink")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReferralSalt")
                        .IsUnique();

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Dal.Entities.RewardTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RewardTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Subscribe to telegram",
                            Reward = 1500
                        },
                        new
                        {
                            Id = 2,
                            Name = "Subscribe to X",
                            Reward = 1500
                        },
                        new
                        {
                            Id = 3,
                            Name = "Subscribe to VK",
                            Reward = 1500
                        },
                        new
                        {
                            Id = 4,
                            Name = "Invite a friend",
                            Reward = 5000
                        },
                        new
                        {
                            Id = 5,
                            Name = "Read whitepaper",
                            Reward = 1000
                        },
                        new
                        {
                            Id = 6,
                            Name = "Complete a quiz",
                            Reward = 3900
                        });
                });

            modelBuilder.Entity("Dal.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CurrentBalance")
                        .HasColumnType("real");

                    b.Property<int?>("CurrentMatchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDailyRewardCollected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLastMatchCollected")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastLoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastRewardedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginStreakCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dal.Entities.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Completed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uncollected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uncompleted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("Dal.Entities.Match", b =>
                {
                    b.HasOne("Dal.Entities.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dal.Entities.UserTask", b =>
                {
                    b.HasOne("Dal.Entities.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
